LTO_ENABLE = yes               # link time optimization -- achieves a smaller compiled size
VIA_ENABLE = yes
IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
ENCODER_MAP_ENABLE = yes
AUTOCORRECT_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = no
DYNAMIC_KEYMAP_ENABLE = yes
RAW_ENABLE = yes
EEPROM_ENABLE = yes
EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = embedded_flash
AUDIO_ENABLE = no         # Disable audio feature if not used
BACKLIGHT_ENABLE = no     # Disable backlight feature if not used
SRC += rgb_settings.c